### ISSUE TITLE
Rolling multiple dice at once

### ISSUE THREAD

**Issue by shoshaikh7** [shoshaikh7/yahtzee#1]
##### WHAT USER STORY YOU ARE WORKING ON:

I am working on the user story "Roll 5 Dice"
##### WHAT YOU ARE TRYING TO DO:

When User clicks on the button "roll" 5 dices should appear.
##### DETAILED DESCRIPTION OF THE BUG/ERROR:

I have created one die, and it rolls when I click on the button, however I cant figure out how to get 5 dice to appear at the anytime.
## WHAT I'VE TRIED

I am trying to create a function where it will it would append 5 divs to #dice-board div when I hit the roll button.

Currently I only have one die working.
## QUESTION

How can I make this make 5 dice instead of 1: 
var rollTheDice = function() {
  var value = null;
  var diceCount = 1;
  for (i = 0; i < diceCount; i++) {
      value = Math.floor(Math.random() \* 6) + 1;
  };
  document.getElementById('dice1').innerHTML = value;
  console.log(value)
};

**Comment by WilliamfShaw** [comment]
Have you tried making the die an object? Allowing you to have as many as you want all with the same functionality?

**Comment by shoshaikh7** [comment]
Should I create a prototype?

**Comment by shoshaikh7** [comment]
Got it to work, kinda just built an array with dice objects.
