### ISSUE TITLE
Categories function

### ISSUE THREAD

**Issue by shoshaikh7** [shoshaikh7/yahtzee#2]
##### WHAT USER STORY YOU ARE WORKING ON:

I am working on the user story "User wants to see what categories are eligible to earn points from."
##### WHAT YOU ARE TRYING TO DO:

I am trying to make functions for each categories.
## WHAT I'VE TRIED

I have created an array of the current dice values, now i am trying to see how i can use that in categories function.
## QUESTION

I just need help getting started on a function where lets say it will see if the dice contain any "ones" and will calculate the score, then eventually add to the main score and disable the category.

**Comment by jasonseminara** [comment]
Is this still relevant?
